import {
  Code2,
  Sparkles,
  Network,
  Regex,
  Boxes,
  SquareFunction,
  ShieldCheck,
  ShieldAlert,
  Bug,
  KeyRound,
  Hash,
  Activity,
  Braces,
  GitCompare,
  CalendarClock,
  Fingerprint,
  FileKey,
  KeySquare,
  Router,
  Lock,
  MonitorPlay,
  type LucideIcon,
} from "lucide-react";
import type { WorkspaceId } from "@/lib/workspaces";

export const WORKSPACE_ICONS: Record<WorkspaceId, LucideIcon> = {
  "code-preview": MonitorPlay,
  "code-review": Code2,
  "refactor-lab": Sparkles,
  "system-design": Network,
  "regex-lab": Regex,
  "api-designer": Boxes,
  "algo-analyzer": SquareFunction,
  "json-lab": Braces,
  "diff-viewer": GitCompare,
  "cron-lab": CalendarClock,
  "uuid-lab": Fingerprint,
  "recon-planner": ShieldCheck,
  "threat-model": ShieldAlert,
  "owasp-audit": Bug,
  "password-analyzer": KeyRound,
  "hash-lab": Hash,
  "cvss-calculator": Activity,
  "jwt-inspector": FileKey,
  "password-generator": KeySquare,
  "subnet-calc": Router,
  "cipher-lab": Lock,
};
