/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentTestRouteImport } from './routes/agent-test'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FilesRouteImport } from './routes/files'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAiPoolStatusRouteImport } from './routes/api/ai-pool-status'
import { Route as ApiAiStreamRouteImport } from './routes/api/ai-stream'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as WorkspacesToolRouteImport } from './routes/workspaces.$tool'
import { Route as ApiPublicGithubCallbackRouteImport } from './routes/api/public/github-callback'
import { Route as ApiPublicHoneypotsAdminRouteImport } from './routes/api/public/honeypots/admin'
import { Route as ApiPublicHoneypotsEnvRouteImport } from './routes/api/public/honeypots/env'
import { Route as ApiPublicHoneypotsGitConfigRouteImport } from './routes/api/public/honeypots/git-config'
import { Route as ApiPublicHoneypotsPhpmyadminRouteImport } from './routes/api/public/honeypots/phpmyadmin'
import { Route as ApiPublicHoneypotsWpLoginRouteImport } from './routes/api/public/honeypots/wp-login'
import { Route as ApiPublicHoneypotsTokenTokenRouteImport } from './routes/api/public/honeypots/token.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTestRoute = AgentTestRouteImport.update({
  id: '/agent-test',
  path: '/agent-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPoolStatusRoute = ApiAiPoolStatusRouteImport.update({
  id: '/api/ai-pool-status',
  path: '/api/ai-pool-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStreamRoute = ApiAiStreamRouteImport.update({
  id: '/api/ai-stream',
  path: '/api/ai-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesToolRoute = WorkspacesToolRouteImport.update({
  id: '/workspaces/$tool',
  path: '/workspaces/$tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGithubCallbackRoute = ApiPublicGithubCallbackRouteImport.update({
  id: '/api/public/github-callback',
  path: '/api/public/github-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHoneypotsAdminRoute = ApiPublicHoneypotsAdminRouteImport.update({
  id: '/api/public/honeypots/admin',
  path: '/api/public/honeypots/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHoneypotsEnvRoute = ApiPublicHoneypotsEnvRouteImport.update({
  id: '/api/public/honeypots/env',
  path: '/api/public/honeypots/env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHoneypotsGitConfigRoute =
  ApiPublicHoneypotsGitConfigRouteImport.update({
    id: '/api/public/honeypots/git-config',
    path: '/api/public/honeypots/git-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHoneypotsPhpmyadminRoute =
  ApiPublicHoneypotsPhpmyadminRouteImport.update({
    id: '/api/public/honeypots/phpmyadmin',
    path: '/api/public/honeypots/phpmyadmin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHoneypotsWpLoginRoute =
  ApiPublicHoneypotsWpLoginRouteImport.update({
    id: '/api/public/honeypots/wp-login',
    path: '/api/public/honeypots/wp-login',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHoneypotsTokenTokenRoute =
  ApiPublicHoneypotsTokenTokenRouteImport.update({
    id: '/api/public/honeypots/token/$token',
    path: '/api/public/honeypots/token/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent-test': typeof AgentTestRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/files': typeof FilesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/ai-pool-status': typeof ApiAiPoolStatusRoute
  '/api/ai-stream': typeof ApiAiStreamRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/workspaces/$tool': typeof WorkspacesToolRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/api/public/github-callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/honeypots/admin': typeof ApiPublicHoneypotsAdminRoute
  '/api/public/honeypots/env': typeof ApiPublicHoneypotsEnvRoute
  '/api/public/honeypots/git-config': typeof ApiPublicHoneypotsGitConfigRoute
  '/api/public/honeypots/phpmyadmin': typeof ApiPublicHoneypotsPhpmyadminRoute
  '/api/public/honeypots/wp-login': typeof ApiPublicHoneypotsWpLoginRoute
  '/api/public/honeypots/token/$token': typeof ApiPublicHoneypotsTokenTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent-test': typeof AgentTestRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/files': typeof FilesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/ai-pool-status': typeof ApiAiPoolStatusRoute
  '/api/ai-stream': typeof ApiAiStreamRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/workspaces/$tool': typeof WorkspacesToolRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/api/public/github-callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/honeypots/admin': typeof ApiPublicHoneypotsAdminRoute
  '/api/public/honeypots/env': typeof ApiPublicHoneypotsEnvRoute
  '/api/public/honeypots/git-config': typeof ApiPublicHoneypotsGitConfigRoute
  '/api/public/honeypots/phpmyadmin': typeof ApiPublicHoneypotsPhpmyadminRoute
  '/api/public/honeypots/wp-login': typeof ApiPublicHoneypotsWpLoginRoute
  '/api/public/honeypots/token/$token': typeof ApiPublicHoneypotsTokenTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent-test': typeof AgentTestRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/files': typeof FilesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/ai-pool-status': typeof ApiAiPoolStatusRoute
  '/api/ai-stream': typeof ApiAiStreamRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/workspaces/$tool': typeof WorkspacesToolRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/api/public/github-callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/honeypots/admin': typeof ApiPublicHoneypotsAdminRoute
  '/api/public/honeypots/env': typeof ApiPublicHoneypotsEnvRoute
  '/api/public/honeypots/git-config': typeof ApiPublicHoneypotsGitConfigRoute
  '/api/public/honeypots/phpmyadmin': typeof ApiPublicHoneypotsPhpmyadminRoute
  '/api/public/honeypots/wp-login': typeof ApiPublicHoneypotsWpLoginRoute
  '/api/public/honeypots/token/$token': typeof ApiPublicHoneypotsTokenTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent-test'
    | '/agents'
    | '/auth'
    | '/diagnostics'
    | '/docs'
    | '/download'
    | '/files'
    | '/help'
    | '/history'
    | '/premium'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/ai-pool-status'
    | '/api/ai-stream'
    | '/api/generate-image'
    | '/workspaces/$tool'
    | '/workspaces/'
    | '/api/public/github-callback'
    | '/api/public/honeypots/admin'
    | '/api/public/honeypots/env'
    | '/api/public/honeypots/git-config'
    | '/api/public/honeypots/phpmyadmin'
    | '/api/public/honeypots/wp-login'
    | '/api/public/honeypots/token/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent-test'
    | '/agents'
    | '/auth'
    | '/diagnostics'
    | '/docs'
    | '/download'
    | '/files'
    | '/help'
    | '/history'
    | '/premium'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/ai-pool-status'
    | '/api/ai-stream'
    | '/api/generate-image'
    | '/workspaces/$tool'
    | '/workspaces'
    | '/api/public/github-callback'
    | '/api/public/honeypots/admin'
    | '/api/public/honeypots/env'
    | '/api/public/honeypots/git-config'
    | '/api/public/honeypots/phpmyadmin'
    | '/api/public/honeypots/wp-login'
    | '/api/public/honeypots/token/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent-test'
    | '/agents'
    | '/auth'
    | '/diagnostics'
    | '/docs'
    | '/download'
    | '/files'
    | '/help'
    | '/history'
    | '/premium'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/ai-pool-status'
    | '/api/ai-stream'
    | '/api/generate-image'
    | '/workspaces/$tool'
    | '/workspaces/'
    | '/api/public/github-callback'
    | '/api/public/honeypots/admin'
    | '/api/public/honeypots/env'
    | '/api/public/honeypots/git-config'
    | '/api/public/honeypots/phpmyadmin'
    | '/api/public/honeypots/wp-login'
    | '/api/public/honeypots/token/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentTestRoute: typeof AgentTestRoute
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  FilesRoute: typeof FilesRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiAiPoolStatusRoute: typeof ApiAiPoolStatusRoute
  ApiAiStreamRoute: typeof ApiAiStreamRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  WorkspacesToolRoute: typeof WorkspacesToolRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
  ApiPublicGithubCallbackRoute: typeof ApiPublicGithubCallbackRoute
  ApiPublicHoneypotsAdminRoute: typeof ApiPublicHoneypotsAdminRoute
  ApiPublicHoneypotsEnvRoute: typeof ApiPublicHoneypotsEnvRoute
  ApiPublicHoneypotsGitConfigRoute: typeof ApiPublicHoneypotsGitConfigRoute
  ApiPublicHoneypotsPhpmyadminRoute: typeof ApiPublicHoneypotsPhpmyadminRoute
  ApiPublicHoneypotsWpLoginRoute: typeof ApiPublicHoneypotsWpLoginRoute
  ApiPublicHoneypotsTokenTokenRoute: typeof ApiPublicHoneypotsTokenTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-test': {
      id: '/agent-test'
      path: '/agent-test'
      fullPath: '/agent-test'
      preLoaderRoute: typeof AgentTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-pool-status': {
      id: '/api/ai-pool-status'
      path: '/api/ai-pool-status'
      fullPath: '/api/ai-pool-status'
      preLoaderRoute: typeof ApiAiPoolStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-stream': {
      id: '/api/ai-stream'
      path: '/api/ai-stream'
      fullPath: '/api/ai-stream'
      preLoaderRoute: typeof ApiAiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$tool': {
      id: '/workspaces/$tool'
      path: '/workspaces/$tool'
      fullPath: '/workspaces/$tool'
      preLoaderRoute: typeof WorkspacesToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github-callback': {
      id: '/api/public/github-callback'
      path: '/api/public/github-callback'
      fullPath: '/api/public/github-callback'
      preLoaderRoute: typeof ApiPublicGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/honeypots/admin': {
      id: '/api/public/honeypots/admin'
      path: '/api/public/honeypots/admin'
      fullPath: '/api/public/honeypots/admin'
      preLoaderRoute: typeof ApiPublicHoneypotsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/honeypots/env': {
      id: '/api/public/honeypots/env'
      path: '/api/public/honeypots/env'
      fullPath: '/api/public/honeypots/env'
      preLoaderRoute: typeof ApiPublicHoneypotsEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/honeypots/git-config': {
      id: '/api/public/honeypots/git-config'
      path: '/api/public/honeypots/git-config'
      fullPath: '/api/public/honeypots/git-config'
      preLoaderRoute: typeof ApiPublicHoneypotsGitConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/honeypots/phpmyadmin': {
      id: '/api/public/honeypots/phpmyadmin'
      path: '/api/public/honeypots/phpmyadmin'
      fullPath: '/api/public/honeypots/phpmyadmin'
      preLoaderRoute: typeof ApiPublicHoneypotsPhpmyadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/honeypots/wp-login': {
      id: '/api/public/honeypots/wp-login'
      path: '/api/public/honeypots/wp-login'
      fullPath: '/api/public/honeypots/wp-login'
      preLoaderRoute: typeof ApiPublicHoneypotsWpLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/honeypots/token/$token': {
      id: '/api/public/honeypots/token/$token'
      path: '/api/public/honeypots/token/$token'
      fullPath: '/api/public/honeypots/token/$token'
      preLoaderRoute: typeof ApiPublicHoneypotsTokenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentTestRoute: AgentTestRoute,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  FilesRoute: FilesRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiAiPoolStatusRoute: ApiAiPoolStatusRoute,
  ApiAiStreamRoute: ApiAiStreamRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  WorkspacesToolRoute: WorkspacesToolRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
  ApiPublicGithubCallbackRoute: ApiPublicGithubCallbackRoute,
  ApiPublicHoneypotsAdminRoute: ApiPublicHoneypotsAdminRoute,
  ApiPublicHoneypotsEnvRoute: ApiPublicHoneypotsEnvRoute,
  ApiPublicHoneypotsGitConfigRoute: ApiPublicHoneypotsGitConfigRoute,
  ApiPublicHoneypotsPhpmyadminRoute: ApiPublicHoneypotsPhpmyadminRoute,
  ApiPublicHoneypotsWpLoginRoute: ApiPublicHoneypotsWpLoginRoute,
  ApiPublicHoneypotsTokenTokenRoute: ApiPublicHoneypotsTokenTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
